---
title: "Python Ireland"
output: 
  flexdashboard::flex_dashboard:
    theme: united
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


Noiceboard {data-navmenu="Introduction"}
=====================================

Column {.tabset}
--------------------

### Contents

|| Section | Conponents ||
|--------|:-------|:---------------------|----------|
| | **Monthly Meetup**| Python Ireland's Montly Meetups  | |
| | **Social Media**| <a href="socialmedia.html"> Python Ireland's Social Media</a> ||
| | **PyCon Ireland 2022**| <a href="2022.html"> Set Theory</a> ||
| | **PyCon Limerick 2023**| <a href="limerick2023.html"> PyCon Limerick 2023</a> ||
| | **PyData Ireland**| <a href="pydata.html"> PyData Ireland</a> ||
| | **Section 7**| Functions 3: O-Notation| |



### Python Ireland


Discrete mathematics is the common name for the fields of mathematics most generally useful in theoretical computer science. This includes computability theory, computational complexity theory, and information theory. 

*  **Computability theory** examines the limitations of various theoretical models of the computer, including the most powerful known model - the Turing machine. 

*  **Complexity theory** is the study of tractability by computer; some problems, although theoretically soluble by computer, are so expensive in terms of time or space that solving them is likely to remain practically unfeasible, even with rapid advance of computer hardware. 

*  Finally, **information theory** is concerned with the amount of data that can be stored on a given medium, and hence concepts such as compression and entropy.
